02.1_HW/PizzaApp - EntityFramework/PizzaApp/PizzaApp/Controllers/CustomerController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Services.Interfaces;
using ViewModels;

namespace PizzaApp.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomerService _customerService;

        public CustomerController(ICustomerService customerService)
        {
            _customerService = customerService;
        }

        public IActionResult Index()
        {
            return View(_customerService.GetAll());
        }

        public IActionResult Details(int id)
        {
            var customer = _customerService.GetById(id);
            return View(customer);
        }

        public IActionResult Edit(int id)
        {
            return View(_customerService.GetById(id));
        }

        public IActionResult Add()
        {
            return View("Edit", new CustomerViewModel());
        }

        [HttpPost]
        public IActionResult Save(CustomerViewModel customer)
        {
            if (customer == null)
            {
                return BadRequest();
            }

            if (!ModelState.IsValid)
            {
                return View("Edit", customer);
            }

            _customerService.Save(customer);

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            _customerService.Delete(id);

            return RedirectToAction("Index");
        }
    }
}

02.1_HW/PizzaApp - EntityFramework/PizzaApp/PizzaApp/Controllers/PizzaController.cs
using System;
using System.Linq;
using DomainModels;
using Microsoft.AspNetCore.Mvc;
using Services.Implementations;
using Services.Interfaces;
using ViewModels;

namespace PizzaApp.Controllers
{
    public class PizzaController : Controller
    {
        private readonly IPizzaService _pizzaService;

        public PizzaController(IPizzaService pizzaService)
        {
            _pizzaService = pizzaService;
        }
        public IActionResult Index()
        {
            var pizzas = _pizzaService.GetAll();
            return View(pizzas);
        }

        public IActionResult Details(int id)
        {
            try
            {
                var pizza = _pizzaService.GetById(id);
                return View(pizza);
            }
            catch (Exception ex)
            {
                return View("Error", ex.Message);
            }
        }

        public IActionResult Edit(int id)
        {
            var pizza = _pizzaService.GetById(id);
            return View(pizza);
        }

        public IActionResult Add()
        {
            return View("Edit", new PizzaViewModel());
        }

        [HttpPost]
        public IActionResult Save(PizzaViewModel pizza)
        {
            if (pizza == null)
            {
                return BadRequest();
            }

            if (!ModelState.IsValid)
            {
                return View("Edit", pizza);
            }

            try
            {
                _pizzaService.Save(pizza);
            }
            catch (Exception ex)
            {
                return View("Error", ex.Message);
            }

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            _pizzaService.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

02.1_HW/PizzaApp - EntityFramework/PizzaApp/PizzaApp/Controllers/PizzaSizeController.cs
using System.Collections.Generic;
using System.Linq;
using DomainModels;
using Microsoft.AspNetCore.Mvc;
using PizzaApp.Helper;
using Services.Interfaces;
using ViewModels;

namespace PizzaApp.Controllers
{
    public class PizzaSizeController : Controller
    {
        private readonly IPizzaSizeService _pizzaSizeService;
        private readonly IPizzaService _pizzaService;
        private readonly ISizeService _sizeService;

        public PizzaSizeController(IPizzaSizeService pizzaSizeService, IPizzaService pizzaService, ISizeService sizeService)
        {
            _pizzaSizeService = pizzaSizeService;
            _pizzaService = pizzaService;
            _sizeService = sizeService;
        }

        public IActionResult Index()
        {
            return View(_pizzaSizeService.GetAll());
        }

        public IActionResult Details(int id)
        {
            return View(_pizzaSizeService.GetById(id));
        }

        public IActionResult Edit(int id)
        {
            List<SizeViewModel> sizes = _sizeService.GetAll();
            ViewBag.SizesForSelection = sizes.ToSelectListItems();

            List<PizzaViewModel> pizzas = _pizzaService.GetAll();
            ViewBag.PizzasForSelection = pizzas.ToSelectListItems();
            return View(_pizzaSizeService.GetById(id));
        }

        public IActionResult Add()
        {
            List<SizeViewModel> sizes = _sizeService.GetAll();
            ViewBag.SizesForSelection = sizes.ToSelectListItems();

            List<PizzaViewModel> pizzas = _pizzaService.GetAll();
            ViewBag.PizzasForSelection = pizzas.ToSelectListItems();

            return View("Edit", new PizzaSizeViewModel());
        }

        public IActionResult Save(PizzaSizeViewModel pizzaSize)
        {
            if (pizzaSize == null)
            {
                return BadRequest();
            }

            if (!ModelState.IsValid)
            {
                return View("Edit", pizzaSize);
            }

            _pizzaSizeService.Save(pizzaSize);

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            _pizzaSizeService.Delete(id);

            return RedirectToAction("Index");
        }
    }
}

02.1_HW/PizzaApp - EntityFramework/PizzaApp/PizzaApp/Controllers/SizeController.cs
using Microsoft.AspNetCore.Mvc;
using Services.Interfaces;
using ViewModels;

namespace PizzaApp.Controllers
{
    public class SizeController : Controller
    {
        private readonly ISizeService _sizeService;

        public SizeController(ISizeService sizeService)
        {
            _sizeService = sizeService;
        }

        public IActionResult Index()
        {
            return View(_sizeService.GetAll());
        }

        public IActionResult Details(int id)
        {
            return View(_sizeService.GetById(id));
        }

        public IActionResult Edit(int id)
        {
            return View(_sizeService.GetById(id));
        }

        public IActionResult Add()
        {
            return View("Edit", new SizeViewModel());
        }

        [HttpPost]
        public IActionResult Save(SizeViewModel size)
        {
            if (size == null)
            {
                return BadRequest();
            }

            if (!ModelState.IsValid)
            {
                return View("Edit", size);
            }

            _sizeService.Save(size);

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            _sizeService.Delete(id);

            return RedirectToAction("Index");
        }
    }
}

02.1_HW/PizzaApp - EntityFramework/PizzaApp/PizzaApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pizza App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/mycss.css"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Pizza App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pizza" asp-action="Index">Pizzas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Size" asp-action="Index">Sizes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PizzaSize" asp-action="Index">Menu</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SEDC - <a asp-area="" asp-controller="Home" asp-action="Index">Pizza App</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>