02.1_HW/PizzaApp - EntityFramework/PizzaApp/PizzaApp/Controllers/OrderItemController.cs
using System.Linq;
using DomainModels;
using Microsoft.AspNetCore.Mvc;
using PizzaApp.Helper;
using Services.Interfaces;
using ViewModels;

namespace PizzaApp.Controllers
{
    public class OrderItemController : Controller
    {
        private readonly IOrderItemService _orderItemService;
        private readonly IPizzaSizeService _pizzaSizeService;

        public OrderItemController(IOrderItemService orderItemService, 
            IPizzaSizeService pizzaSizeService)
        {
            _orderItemService = orderItemService;
            _pizzaSizeService = pizzaSizeService;
        }

        public IActionResult Add(int id)
        {
            OrderItemViewModel orderItemViewModel = _orderItemService.CreateNewOrderItem(id);

            ViewBag.PizzaSizesForSelect = _pizzaSizeService.GetAll().ToSelectListItems();
            return View(orderItemViewModel);
        }

        [HttpPost]
        public IActionResult Save(OrderItemViewModel orderItem)
        {
            if (orderItem == null)
            {
                return BadRequest();
            }

            if (!ModelState.IsValid)
            {
                return View("Add", orderItem);
            }

            _orderItemService.Save(orderItem);


            return RedirectToAction("Details", "Order", new { Id = orderItem.OrderId });
        }

        public IActionResult Delete(int id)
        {
            var orderItem = _orderItemService.GetById(id);
            _orderItemService.Delete(id);

            return RedirectToAction("Details", "Order", new { Id = orderItem.OrderId });
        }
    }
}

02.1_HW/PizzaApp - EntityFramework/PizzaApp/PizzaApp/Views/OrderItem/Add.cshtml
@model ViewModels.OrderItemViewModel

    <form asp-controller="OrderItem" asp-action="Save">
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="OrderId" />
        <div class="form-group">
            <label asp-for="PizzaSizeId"></label>
            <select asp-for="PizzaSizeId" asp-items="ViewBag.PizzaSizesForSelect" class="form-control">
                <option value=""> - Please select pizza - </option>
            </select>
            <span asp-validation-for="PizzaSizeId" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Quantity"></label>
            <input asp-for="Quantity" class="form-control" />
            <span asp-validation-for="Quantity" class="text-danger"></span>
        </div>
        <input type="submit" value="Save" class="btn btn-primary"/>
        <a asp-controller="Order" asp-action="Details" asp-route-id="@Model.OrderId" class="btn btn-warning">Cancel</a>
    </form>